version: "3"
services:
  app:
    image: quay.io/hedgedoc/hedgedoc:1.7.2
    restart: always
    env_file:
      - .env
    expose:
      - 3000
    volumes:
      - ./data:/hedgedoc/data:rw
      - ./uploads:/hedgedoc/public/uploads:rw

networks:
  default:
    external:
      name: nginx-proxy
