version: "3"
services:
  app:
    image: quay.io/hedgedoc/hedgedoc:1.7.2
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./data:/hedgedoc/data
      - ./uploads:/hedgedoc/public/uploads
